---
model:
  base filters: 32
  channels: 3
train:
  noise level: 50
  patch size: 64
  batch size: 16
  learning rate: 1.e-4
  weight decay: 1.e-5
  scheduler gamma: 0.5
  scheduler step: 3
  epochs: 21
  dataset splits: 10
  # device: cuda:0
  device: cpu
  multi gpu: false
  workers: 10
  dataset path: 'data/0'
  checkpoint path: 'Checkpoints'
val:
  noise levels:
    - 10
    - 30
    - 50
  patch size: 256
  batch size: 16
  frequency: 1
  workers: 24
  dataset path: 'data/0'
test:
  noise levels:
    - 10
    - 30
    - 50
  # device: cuda:0
  device: cpu
  padding: true
  dataset path: 'Datasets/Test'
  results path: 'Results'
  pretrained models path: 'Pretrained'
  save images: true
...
